version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432/tcp
    environment:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069/tcp"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  djan:
      build: .
      volumes:
        - .:/djan
      ports:
        - 8080:8080
      image: django:djan
      container_name: djan
      command: python manage.py runserver 0.0.0.0:8080
      depends_on:
        - db
      
volumes:
  postgres_data:
  db-data:
    driver: local
  web-data:
    driver: local